### ISSUE TITLE
Response Code 500 - Invalid Memory Address

### ISSUE THREAD

**Issue by JoshCode** [caser/slack_auto_invites#3]
I am getting 500 errors. I tried to do a little investigating, but I wasn't able to fix it.

```
panic: runtime error: invalid memory address or nil pointer dereference

goroutine 20 [running]:
main82513.SendInvite(0xc0104aaea0, 0xc01041eac6, 0x4, 0xc01041eaed, 0x4, 0xc010454f40, 0x13, 0x0, 0x0)
    invite.go:65 +0x6a5
main82513.inviteHandler(0x7f0c056392c0, 0xc01042fa80, 0xc0104aaea0)
    invite.go:83 +0x1d3
net/http.HandlerFunc.ServeHTTP(0xb5c138, 0x7f0c056392c0, 0xc01042fa80, 0xc0104aaea0)
    go/src/net/http/server.go:1265 +0x56
net/http.(*ServeMux).ServeHTTP(0xc01045e750, 0x7f0c056392c0, 0xc01042fa80, 0xc0104aaea0)
    go/src/net/http/server.go:1541 +0x1b4
appengine_internal.executeRequestSafely(0xc01042fa80, 0xc0104aaea0)
    go/src/appengine_internal/api_prod.go:288 +0xb7
appengine_internal.(*server).HandleRequest(0xce8860, 0xc0104017a0, 0xc01049c480, 0xc010431040, 0x0, 0x0)
    go/src/appengine_internal/api_prod.go:222 +0x102b
reflect.Value.call(0x9bc720, 0xce8860, 0x113, 0xa3e7a0, 0x4, 0xc0104c5f78, 0x3, 0x3, 0x0, 0x0, ...)
    /tmp/appengine/go/src/reflect/value.go:419 +0x10fd
reflect.Value.Call(0x9bc720, 0xce8860, 0x113, 0xc0104c5f78, 0x
```

**Comment by JoshCode** [comment]
Well, I guess there will never be an answer to this one ;P
